---
title: "Receipt analysis (post-study)"
author: "Remco Benthem de Grave"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r}
library(tidyverse)
library(magrittr)
library(here)
library(lattice) #density plot
library(car) #qqplot
library(lme4)

#read-in the receipts
receipt_data <- read_csv(here("data","processed","receipt_level_data.csv"))
```



```{r}

# library(lme4)
```


```{r}
#visualize receipt dates

#determine start-date normalized receipt dates (days since start)
receipt_data %<>% 
  mutate(day_recorded = difftime(date_recorded, hh_start, units = "days")) 

receipt_data %>% 
  ggplot(aes(x = as.numeric(day_recorded), y = rcpt_C02_ave)) +
  geom_point() +
  geom_line() +
  facet_wrap(.~household_ID) + 
  theme_light() + 
  labs(y = "Weight-adjusted average gCO2/100g", x = "Receipt date (days since start)")
```


## Visualize change of average receipt print over time

```{r}
#visualize the trends
receipt_data %>% 
  ggplot(aes(x = receipt_id, y = rcpt_C02_ave)) +
  geom_point() +
  geom_line() +
  facet_wrap(.~household_ID) + 
  theme_light() + 
  labs(y = "Weight-adjusted average gCO2/100g", x = "Receipt number (chronological)")

#Weight-adjusted refers to the weight of individual items is factored into the calculation
#Data was loaded into the app before the participant started. This is accounted in receipt #1

```

## Determine whether there is statistical evidence of footprint changing over time

```{r}

#mixed-model to calculate change

#center the independent variable
rcpt_data_v2$receipt_id_c <- scale(rcpt_data_v2$receipt_id, center = TRUE, scale = FALSE)

#full model
m_full <- lmer(rcpt_C02_ave ~ receipt_id_c + (1 + receipt_id_c | household_ID), data = rcpt_data_v2)
summary(m_full)

#null model (inteaction only)
m_null <- lmer(rcpt_C02_ave ~ 1 + (1 | household_ID), data = rcpt_data_v2)
summary(m_null)
```

```{r}
densityplot(resid(m_full, scaled = TRUE))
qqPlot(resid(m_full, scaled = TRUE))
plot(m_full, household_ID ~ resid(., scaled = TRUE))
plot(m_full, type = c('p', 'smooth'))
# potential problems. Outliers in the residuals
```


```{r}
anova(m_null,m_full)
```


## Determine whether there is statistical evidence of footprint changing over time -- using days since start

```{r}

#mixed-model to calculate change

#center the independent variable
rcpt_data_v2$day_recorded_c <- scale(as.numeric(rcpt_data_v2$day_recorded), center = TRUE, scale = FALSE)

#full model
m_full <- lmer(rcpt_C02_ave ~ day_recorded + (1 + day_recorded | household_ID), data = rcpt_data_v2)
summary(m_full)

#null model (inteaction only)
m_null <- lmer(rcpt_C02_ave ~ 1 + (1 | household_ID), data = rcpt_data_v2)
summary(m_null)
```

```{r}
densityplot(resid(m_full, scaled = TRUE))
qqPlot(resid(m_full, scaled = TRUE))
plot(m_full, household_ID ~ resid(., scaled = TRUE))
plot(m_full, type = c('p', 'smooth'))
# potential problems. Outliers in the residuals
```


```{r}
anova(m_null,m_full)
```


## Non-parametric test of time impact
```{r}
#create dataframe for ski.mack -- 'missing' observation have to be present in the df as NA
#this can easily be achieved by turning the data into a wide structure. Each row needs to be a group (household)
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2761045/
# https://en.wikipedia.org/wiki/Friedman_test#cite_note-6


library(Skillings.Mack)

skimack_data <- receipt_data %>% select(household_ID, receipt_id, rcpt_C02_ave)
# skimack_data %<>% pivot_wider(names_from = receipt_id, values_from = rcpt_C02_ave)
# skimack_data %<>% select(!household_ID)
# skimack_data %<>% select(!13)
# skimack_data %>% as.matrix() %>% Ski.Mack(.)
skimack_data %<>% pivot_wider(names_from = household_ID, values_from = rcpt_C02_ave)
skimack_data %<>% select(!receipt_id)
skimack_data %>% as.matrix() %>% Ski.Mack(.) #there is no clear difference in receipt number
```

```{r}
#alternative: compare first with all future receipts
receipt_data %<>% 
  group_by(household_ID) %>%
  mutate(date_third = ceiling(round(3*day_recorded/max(as.numeric(day_recorded)), digits = 2))) %>%
  mutate(date_third = ifelse(date_third == 0, 1, date_third)) #day zero is assigned to the first third

#calculate the average footprint by third
test <- receipt_data %>% 
  group_by(household_ID, date_third) %>%
  mutate(
    period_footprint_total = sum(rcpt_C02_total),
    period_weight_total = sum(rcpt_weight),
    period_footprint_ave = sum(rcpt_C02_total)/sum(rcpt_weight), .after = rcpt_C02_ave
  )

test <- receipt_data %>% 
  group_by(household_ID, date_third) %>%
  reframe(
    period_footprint_total = sum(rcpt_C02_total),
    period_weight_total = sum(rcpt_weight),
    period_footprint_ave = sum(rcpt_C02_total)/sum(rcpt_weight)
  )

test %>% 
  filter(date_third != 2) %>%
  ggplot(aes(x = date_third, y = period_footprint_total, group = household_ID)) + 
  geom_line()

ttest_data <- 
  test %>% 
  select(household_ID,date_third,period_footprint_ave) %>% 
  mutate(date_third = paste0("period.",date_third)) %>%
  pivot_wider(names_from = date_third, values_from = period_footprint_ave)

t.test(x = ttest_data$period.1, y = ttest_data$period.3, paired = T)
```


```{r eval=FALSE, include=FALSE}
#---discard this. rm ANOVA does not work with 'missing' values
#https://www.theanalysisfactor.com/when-repeated-measures-anova-not-work-for-repeated-measures-data/
#test effect (repeated measures)

# library("rstatix")
rcpt_data_v2 %<>% mutate(household_ID = factor(household_ID), receipt_id = as.numeric(receipt_id))

res.aov <- anova_test(data = rcpt_data_v2, dv = rcpt_C02_ave, wid = household_ID, within = receipt_id)
get_anova_table(res.aov)
```